### ISSUE TITLE
Mod deprecated ?

### ISSUE THREAD

**Issue by Kunjo87** [FocusedFault/EnemiesPlus#3]
Hello,

First a big big thanks for this mod but mostly for all what you did for the community !

As the title say, the EnnemiesPlus Mod is indicated as deprecated since today on Thunderstore and R2Modman's manager. Since it's one of the mods that is enabled at all time on my setup and that the last official RoR2's update didn't seem to mess with it, I was wondering if that's coming from you, if a dependency's update broke it or if it's just a bug from Thunderstore ?

Is the mod still playable in that state ? Is it replaced or included in another mod ? I disables it for now but should we expect an update or just uninstall it ?

Thanks again !

Regards.

**Comment by goldenguy00** [comment]
sad day :( beetles just aint the same without it

**Comment by Nuxlar** [comment]
it was playable until the most recent Gearbox update, I'll most likely not update this mod though there is someone who might maintain it instead, if they update it to the most recent DLC update I'll post the link here and in the mod page most likely

**Comment by Kunjo87** [comment]
Thanks for your answer !
It was indicated as deprecated a few days before the SOTS release though, that's why I was asking.
I really hope someone will port your work to SOTS and maintain it!

Regards.

**Comment by goldenguy00** [comment]
im working on a fixed up version atm https://github.com/goldenguy00/EnemiesPlusPlus

**Comment by goldenguy00** [comment]
Likely will be a continuation instead of a direct port if that's ok (that's generally the case for anything that i do)

**Comment by Nuxlar** [comment]
Score will be maintaining the mod from now on, check it out here https://thunderstore.io/package/score/EnemiesPlusPlus/
